import 'dart:convert';

import 'package:http/http.dart' as http;

const Map<String, String> currenciesList = {
  "AAA": "",
  "AFN": "Afghan afghani",
  "ALL": "Albanian lek",
  "DZD": "Algerian dinar",
  "AOA": "Angolan kwanza",
  "ARS": "Argentine peso",
  "AMD": "Armenian dram",
  "AWG": "Aruban florin",
  "AUD": "Australian dollar",
  "AZN": "Azerbaijani manat",
  "BSD": "Bahamian dollar",
  "BHD": "Bahraini dinar",
  "BDT": "Bangladeshi taka",
  "BBD": "Barbadian dollar",
  "BYN": "Belarusian ruble",
  "BZD": "Belize dollar",
  "BMD": "Bermudian dollar",
  "BTN": "Bhutanese ngultrum",
  "BOB": "Bolivian boliviano",
  "BAM": "Bosnia and Herzegovina convertible mark",
  "BWP": "Botswana pula",
  "BRL": "Brazilian real",
  "BND": "Brunei dollar",
  "BGN": "Bulgarian lev",
  "MMK": "Burmese kyat",
  "BIF": "Burundian franc",
  "XPF": "CFP franc",
  "KHR": "Cambodian riel",
  "CAD": "Canadian dollar",
  "CVE": "Cape Verdean escudo",
  "KYD": "Cayman Islands dollar",
  "XAF": "Central African CFA franc",
  "CLP": "Chilean peso",
  "COP": "Colombian peso",
  "KMF": "Comorian franc",
  "CDF": "Congolese franc",
  "CRC": "Costa Rican colón",
  "HRK": "Croatian kuna",
  "CUC": "Cuban convertible peso",
  "CUP": "Cuban peso",
  "CZK": "Czech koruna",
  "DKK": "Danish krone",
  "DJF": "Djiboutian franc",
  "DOP": "Dominican peso",
  "XCD": "Eastern Caribbean dollar",
  "EGP": "Egyptian pound",
  "ERN": "Eritrean nakfa",
  "ETB": "Ethiopian birr",
  "EUR": "Euro",
  "FKP": "Falkland Islands pound",
  "FJD": "Fijian dollar",
  "GMD": "Gambian dalasi",
  "GEL": "Georgian lari",
  "GHS": "Ghanaian cedi",
  "GIP": "Gibraltar pound",
  "XAU": "Gold (troy ounce)",
  "GTQ": "Guatemalan quetzal",
  "GGP": "Guernsey pound",
  "GNF": "Guinean franc",
  "GYD": "Guyanese dollar",
  "HTG": "Haitian gourde",
  "HNL": "Honduran lempira",
  "HKD": "Hong Kong dollar",
  "HUF": "Hungarian forint",
  "ISK": "Icelandic króna",
  "INR": "Indian rupee",
  "IDR": "Indonesian rupiah",
  "IRR": "Iranian rial",
  "IQD": "Iraqi dinar",
  "ILS": "Israeli new shekel",
  "JMD": "Jamaican dollar",
  "JPY": "Japanese yen",
  "JEP": "Jersey pound",
  "JOD": "Jordanian dinar",
  "KZT": "Kazakhstani tenge",
  "KES": "Kenyan shilling",
  "KWD": "Kuwaiti dinar",
  "KGS": "Kyrgyzstani som",
  "LAK": "Lao kip",
  "LBP": "Lebanese pound",
  "LSL": "Lesotho loti",
  "LRD": "Liberian dollar",
  "LYD": "Libyan dinar",
  "MOP": "Macanese pataca",
  "MKD": "Macedonian denar",
  "MGA": "Malagasy ariary",
  "MWK": "Malawian kwacha",
  "MYR": "Malaysian ringgit",
  "MVR": "Maldivian rufiyaa",
  "IMP": "Manx pound",
  "MRU": "Mauritanian ouguiya",
  "MUR": "Mauritian rupee",
  "MXN": "Mexican peso",
  "MDL": "Moldovan leu",
  "MNT": "Mongolian tögrög",
  "MAD": "Moroccan dirham",
  "MZN": "Mozambican metical",
  "NAD": "Namibian dollar",
  "NPR": "Nepalese rupee",
  "ANG": "Netherlands Antillean guilder",
  "TWD": "New Taiwan dollar",
  "NZD": "New Zealand dollar",
  "NIO": "Nicaraguan córdoba",
  "NGN": "Nigerian naira",
  "NOK": "Norwegian krone",
  "OMR": "Omani rial",
  "PKR": "Pakistani rupee",
  "PAB": "Panamanian balboa",
  "PGK": "Papua New Guinean kina",
  "PYG": "Paraguayan guaraní",
  "PEN": "Peruvian sol",
  "PHP": "Philippine peso",
  "PLN": "Polish złoty",
  "GBP": "Pound sterling",
  "QAR": "Qatari riyal",
  "CNY": "Renminbi",
  "RON": "Romanian leu",
  "RUB": "Russian ruble",
  "RWF": "Rwandan franc",
  "SHP": "Saint Helena pound",
  "SVC": "Salvadoran colón",
  "WST": "Samoan tālā",
  "SAR": "Saudi riyal",
  "RSD": "Serbian dinar",
  "SCR": "Seychellois rupee",
  "SLL": "Sierra Leonean leone",
  "XAG": "Silver (troy ounce)",
  "SGD": "Singapore dollar",
  "SBD": "Solomon Islands dollar",
  "SOS": "Somali shilling",
  "ZAR": "South African rand",
  "KRW": "South Korean won",
  "SSP": "South Sudanese pound",
  "XDR": "Special drawing rights",
  "LKR": "Sri Lankan rupee",
  "SDG": "Sudanese pound",
  "SRD": "Surinamese dollar",
  "SZL": "Swazi lilangeni",
  "SEK": "Swedish krona",
  "CHF": "Swiss franc",
  "SYP": "Syrian pound",
  "STN": "São Tomé and Príncipe dobra",
  "TJS": "Tajikistani somoni",
  "TZS": "Tanzanian shilling",
  "THB": "Thai baht",
  "TOP": "Tongan paʻanga",
  "TTD": "Trinidad and Tobago dollar",
  "TND": "Tunisian dinar",
  "TRY": "Turkish lira",
  "TMT": "Turkmenistan manat",
  "UGX": "Ugandan shilling",
  "UAH": "Ukrainian hryvnia",
  "AED": "United Arab Emirates dirham",
  "USD": "United States dollar",
  "UYU": "Uruguayan peso",
  "UZS": "Uzbekistani soʻm",
  "VUV": "Vanuatu vatu",
  "VES": "Venezuelan bolívar",
  "VND": "Vietnamese đồng",
  "XOF": "West African CFA franc",
  "YER": "Yemeni rial",
  "ZMW": "Zambian kwacha",
  "ZWL": "Zimbabwean dollar"
};

const accessKey = "6a521ccda5e8fe0f5223ce9e0b2c0d2caa5c583f";
const currencyAPIURL = "https://api.getgeoapi.com/v2/currency/convert";

// This connects to the API for currency conversion.
class CurrencyData {
  Future<double> getCurrencyData({
    required String baseCurrency,
    required String targetCurrency,
    required double amount,
  }) async {
    String preRequestUrl =
        "$currencyAPIURL?api_key=$accessKey&from=$baseCurrency&to=$targetCurrency&amount=$amount&format=json";
    Uri requestURL = Uri.parse(preRequestUrl);
    http.Response response = await http.get(requestURL);
    var decodedData = jsonDecode(response.body);
    var rate = decodedData['rates'][targetCurrency]['rate_for_amount'];
    return (double.parse(rate));
  }
}
